import Head from 'next/head';
import CardList from '../components/CardList';
import HeroIntroduction from '../components/HeroIntroduction';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>The Nest Housing Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner + Introduction */}
      <HeroIntroduction/>

      {/* Highlight */}
      <CardList/>

      {/* Reviews */}


      {/* Footer */}
      
    </div>
  )
}
